### ISSUE TITLE
运行一段时间后出现502错误

### ISSUE THREAD

**Issue by lovejiaxu** [xujimu/ios_super_sign_docker#2]
运行一两天后就显示502 bad getway
查看nginx日志显示：
2022/03/20 [01:52:58]() 【error】 974#974: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 182.151.125.62, server: www.xxx.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "www.xxx.com"
2022/03/20 01:52:58 【error】 974#974: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 182.151.125.62, server: www.xxx.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8080/favicon.ico", host: "www.tanwanmt.top", referrer: "https://www.xxx.com/"

**Comment by lovejiaxu** [comment]
今天重新架设了一次正常了，发现之前502是因为JAVA无缘无故关闭了进程，重启也没能运行。具体的日志因为重装后没去看。
但是估计运行个一两天还会出现这种问题，之前观察了两次都有这现象

**Comment by xiaoxinyougui** [comment]
> 运行一两天后就显示502 bad getway 查看nginx日志显示： 2022/03/20 01:52:58 【error】 974#974: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 182.151.125.62, server: [www.xxx.com](http://www.xxx.com), request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "www.xxx.com" 2022/03/20 01:52:58 【error】 974#974: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 182.151.125.62, server: [www.xxx.com](http://www.xxx.com), request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8080/favicon.ico", host: "www.tanwanmt.top", referrer: "https://www.xxx.com/"

我是装上就报这个错误。网上查资料改了。也没用，继续报这个错误。

**Comment by xiaoxinyougui** [comment]
> 

严重怀疑是https证书不对

**Comment by xiaoxinyougui** [comment]
> 

readme有说要ca证书

**Comment by lovejiaxu** [comment]
> > 
> 
> 严重怀疑是https证书不对

不是证书的问题。我已经放弃这套了。前几天502我去看了日志居然被入侵过，不敢用了。docker我搞不明白。现在在找其他的源码

**Comment by ffoocn** [comment]
请问有找到新的源码嘛> > > 
> 
> > 
> 
> > 严重怀疑是https证书不对
> 
> 
> 
> 不是证书的问题。我已经放弃这套了。前几天502我去看了日志居然被入侵过，不敢用了。docker我搞不明白。现在在找其他的源码

**Comment by ldj888** [comment]
> 
有找到新的源码吗？能不能告知一下谢谢了

**Comment by xujimu** [comment]
> > > 
> > 
> > 
> > 严重怀疑是https证书不对
> 
> 不是证书的问题。我已经放弃这套了。前几天502我去看了日志居然被入侵过，不敢用了。docker我搞不明白。现在在找其他的源码

被入侵过? 日志贴出来看下 我并没有做安全测试  这个问题已经在新版本修复了
